[package]
name = "image-matching-rs"
version = "0.1.4"
edition = "2024"

[dependencies]
image = { version = "0.25.9", features = ["png"] }
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rustfft = "6.4.1"
rayon = "1.11.0"
num-complex = "0.4.6"
